### ISSUE TITLE
The checkPath is not precise enough

### ISSUE THREAD

**Issue by nkiesel** [manuwarfare/abbtr#1]
Having PATH="/home/abc/.local/bin1:/usr/local/bin" would make this code think that ".local/bin" is in the path. I would split the path by ":" and then look for the ".local/bin" in the returned list.

**Comment by manuwarfare** [comment]
Im interested in this. But could you provide more details? Thanks!

(Sorry to close the bug, was a mistake and is now reopended)

**Comment by manuwarfare** [comment]
Ok, got it! Thank you very much for pointing out this bug.
It will be fixed in version 1.0.3, soon!

**Comment by manuwarfare** [comment]
Solved in new version 1.0.3 :+1: 
thanks @nkiesel
